name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      # Step 3: Install Buildozer and dependencies
      - name: Install Buildozer and dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential libffi-dev python3-dev python3-venv openjdk-11-jdk unzip
          pip install --upgrade pip
          pip install buildozer cython==0.29.36

      # Step 4: Install Android Command-Line Tools
      - name: Install Android SDK and Tools
        run: |
          sudo mkdir -p /usr/lib/android-sdk/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
          sudo unzip cmdline-tools.zip -d /usr/lib/android-sdk/cmdline-tools
          sudo mv /usr/lib/android-sdk/cmdline-tools/cmdline-tools /usr/lib/android-sdk/cmdline-tools/latest
          export ANDROID_SDK_ROOT=/usr/lib/android-sdk
          export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools:$PATH
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-31" "build-tools;31.0.0" "tools"

      # Step 5: Verify AIDL Installation
      - name: Verify AIDL Tool
        run: |
          export ANDROID_SDK_ROOT=/usr/lib/android-sdk
          export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools:$PATH
          if [ ! -f "$ANDROID_SDK_ROOT/platform-tools/aidl" ]; then
            echo "AIDL tool is missing!"
            exit 1
          fi

      # Step 6: Build APK
      - name: Build APK
        run: |
          export ANDROID_SDK_ROOT=/usr/lib/android-sdk
          export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools:$PATH
          buildozer android debug
        env:
          ANDROID_SDK_ROOT: /usr/lib/android-sdk

      # Step 7: Upload APK
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: MyApp-APK
          path: bin/*.apk
